# Generated by Django 4.2.4 on 2023-08-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookstore_app.books', verbose_name='Книги'),
        ),
    ]
